# Site settings
title: AC_Von's Blog
email: f.vogang@gmail.com
description: "Python,HTML,CSS,Machine Leaning"
permalink: /:year/:month/:day/:title.html
baseurl: ""
url: "http://vongang.github.io"
atom-baseurl: "http://vongang.github.io"
author: "vongang"

# Build settings
# permalink: date

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks,no_intra_emphasis,strikethrough,no_intra_emphasis,autolink,tables]

#duoshuo
  comments :
    provider : duoshuo
    duoshuo :
      short_name : vongang

navigations:
  - title: About
    class: fa fa-list-ul
    href: /about/
  - title: Blogs
    class: fa fa-tags
    href: /blogs/
  - title: Categories
    class: fa fa-user
    href: /categories/
  - title: Tags
    class: fa fa-film
    href: /tags/
  - title: Rss
    class: fa fa-rss
    href: /atom.xml
